#!/usr/bin/env bash
# Transfer a file from a client to a server
# accepts four parameters as command line arguments
# there are then used with the scp command
if [ "$#" -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
	
