#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.\*

echo \
	        "
frontend localnodes
        bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 491465-web-01 100.26.214.241
	server 491465-web-02 54.237.43.234" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
