#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
# You must use the until loop (for and while are forbidden).
number=0
until [ "$number" -ge 10 ]; do
	echo "Best School"
	number=$((number + 1))
done
