#!/usr/bin/env bash
# In this first debugging project, I will need to get Apache to run on the container and 
# to return a page containing Hello Holberton when querying the root of it.
docker exec -ti ed980bcf357f  /bin/bash
echo "Hello Holberton" >> /var/www/html/index.html
service apache2 start
exit


